services:
  - type: web
    name: naikfoods-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: USER_JWT_SECRET
        generateValue: true
